version: 3.7

networks:
  evonet:
    driver: overlay

services:

  spectrolus:
    build: spectrolus
    networks:
      - spectronet

  spectrologger:
    image: spectrologger
    build:
      context: .
    networks:
      - evonet

  redis:
    image: redis
    networks:
      - evonet