version: "3.7"

networks:
  evo-net:

services:

  redis:
    image: redis:5.0.5-alpine
    networks:
      - evo-net

  spectrolus:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - evo-net

  spectrologger:
    image: spectrologger
    build:
      context: .
      dockerfile: DockerfileSpectroLogger
    networks:
      - evo-net